spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
server:
  servlet:
    session:
      cookie:
        http-only: true     # 세션 쿠키를 HttpOnly로 설정 (JS에서 접근 불가)
        secure: true       # HTTPS 전용 전송 (Https -> true로 바꿔야 함)
        same-site: Lax      # CSRF 방지
      timeout: 30m          # 세션 타임아웃 30분 (30 minutes)
  address: 0.0.0.0

# Swagger 설정
springdoc:
  packages-to-scan: backend.pirocheck
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs
  cache:
    disabled: true