name: Notify Discord on PR

on:
  pull_request:
    types: [opened, synchronize]  # PR 생성 또는 커밋 추가 시

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"[PR #${{ github.event.pull_request.number }}](${{ github.event.pull_request.html_url }}) **${{ github.event.pull_request.title }}** by @${{ github.actor }}\"}" \
               "$DISCORD_WEBHOOK_URL"
